# Generated by Django 6.1.1 on 2026-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
